### ISSUE TITLE
Folder icons generate very small

### ISSUE THREAD

**Issue by luc-ass** [shariati/OS-Folder-Icons#140]
Hey there, thanks for putting this script together. I just added two icons for NextCloud and Dropbox, but the resulting icons have a pretty small logo on them. Have you had this before?

Thanks for helping out!

Input:
`images > masks > Filesharing > Nextcloud & Dropbox`
![dropbox](https://github.com/shariati/OS-Folder-Icons/assets/3263257/993fd414-0c8b-4561-bafb-6414753c02e9)
![nextcloud](https://github.com/shariati/OS-Folder-Icons/assets/3263257/0cce303c-daae-4872-98a1-67a794e90083)

Output (512x512):
![folder_main-dropbox](https://github.com/shariati/OS-Folder-Icons/assets/3263257/4e2d5b10-ce3c-413b-80e0-ae49b3e60c2d)
![folder_main-nextcloud](https://github.com/shariati/OS-Folder-Icons/assets/3263257/3dcec5ce-3478-41ff-88ce-b8b2c61e4c88)

**Comment by shariati** [comment]
Hi @luc-ass, 
Sorry for the delay in getting back to you. You can set the proportion in `src/main.py`:
```python
        # Apply the mask image to the base image
        combined_image = apply_mask(
            base_image_path, mask_image_path, os_folder_config, proportion=0.4, alpha=0.25)
```
