### ISSUE TITLE
Windows 10 Default Folder Icon

### ISSUE THREAD

**Issue by manisoft** [shariati/OS-Folder-Icons#64]
![untitled](https://user-images.githubusercontent.com/19328465/33272983-24ec76c4-d3a1-11e7-9d6d-5e5fa019704e.png)
![pic](https://user-images.githubusercontent.com/19328465/33273362-53e6ad9a-d3a2-11e7-8da3-50f8ba61619d.png)
![font](https://user-images.githubusercontent.com/19328465/33273363-541d49fe-d3a2-11e7-9a23-7b56ad428c98.png)
![modern](https://user-images.githubusercontent.com/19328465/33273364-545febf6-d3a2-11e7-8663-a95f5fd82fa1.png)
![default](https://user-images.githubusercontent.com/19328465/33273366-549b0ba0-d3a2-11e7-8b7a-247376893960.png)
![top](https://user-images.githubusercontent.com/19328465/33273367-54ca20ca-d3a2-11e7-808e-a6b7162d2011.png)
![bot](https://user-images.githubusercontent.com/19328465/33273368-54fc6c60-d3a2-11e7-93d6-8f4c657c0b36.png)

**Comment by shariati** [comment]
Regrettably, this configuration differs from the standard operating system directories, and I have made the decision to support Windows 11 folder icon and onwards.
