### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by laveur** [shariati/OS-Folder-Icons#81]
- Arduino Electronics Platform
- Generic Electronic Schematic Icon
- Fusion 360/3D Model
- Generic Development Icon

Thanks for the great icons! And keep up the good work.

**Comment by shariati** [comment]
@laveur I have added it to backlog will start working on it very soon

**Comment by shariati** [comment]
@laveur requested masks have been added:

**Mask added in Development:**
- Arduino Electronics Platform
- Generic Electronic Schematic Icon
- Generic Development Icon

**Mask added in Design:**
- Fusion 360/3D Model

Please follow the instructions in `README.md` to generate the folder images.
