### ISSUE TITLE
General Mac Icon

### ISSUE THREAD

**Issue by shawnkhoo00** [shariati/OS-Folder-Icons#84]
Hi, wanted to ask if I can get just a Mac icon with no logo on the folder icon for Windows?

**Comment by shariati** [comment]
Thanks, @shawnkhoo00 I will add that on the next update. Sorry for my late response as I was very busy.

**Comment by shawnkhoo00** [comment]
> Thanks, @shawnkhoo00 I will add that on the next update. Sorry for my late response as I was very busy.

It's alright. Take your time haha. No rush.

**Comment by shariati** [comment]
Hi @shawnkhoo00, You can now find the base images (OS Folders Icons) in `images/os_folders`
