### ISSUE TITLE
General 'Code' Icon

### ISSUE THREAD

**Issue by bacarpenter** [shariati/OS-Folder-Icons#85]
I would like to request a more general code icon, for example: </>. A "Hello, world" one would be cool too!

**Comment by MeowyAsh** [comment]
[how's this?](https://cdn.discordapp.com/attachments/840426706236997633/850094720436535346/coding.icns) (it's usibng the big sur folder icon though)

**Comment by shariati** [comment]
Thanks, @bacarpenter for your suggestion. I will be updating the icons soon.
@MeowyAsh thanks for your comment. This issue will be solved in the next update.

**Comment by shariati** [comment]
Added in #104
