### ISSUE TITLE
Mac OS - BigSur folder version

### ISSUE THREAD

**Issue by eriknyk** [shariati/OS-Folder-Icons#88]
can we update the folder image for the bigSur Mac os version, since it is slightly different from previous?

BigSur

![image](https://user-images.githubusercontent.com/205721/107066214-af1e5000-67ab-11eb-9d5c-fb831b2893dd.png)

Current in repo

![image](https://user-images.githubusercontent.com/205721/107066430-f6a4dc00-67ab-11eb-956c-0ec651630e29.png)

**Comment by neoighodaro** [comment]
This would be lovely! Thanks! Alternatively, maybe adding the source files would open the way up for pull requests

**Comment by shariati** [comment]
Sorry, @eriknyk Was really busy and missed your message. I am planning to refresh the repo hopefully soon. and thanks @neoighodaro I'm actually busy moving the icon source file to Figma. I will share the Link later.

**Comment by simkimsia** [comment]
can you also share your method and a blank folder icon so we can DIY?

**Comment by shariati** [comment]
I have updated to MacOS Ventura and created a script to generate for any other operating system.
Please check #103
