### ISSUE TITLE
Contribution: Games folder icon for macOS

### ISSUE THREAD

**Issue by Swiss-Mac-User** [shariati/OS-Folder-Icons#90]
I‘m the creator of these macOS specific and generic «Games» folder icons. You can add them to your library if you want:

* [macOS 12 Monterey](https://swissmacuser.ch/macos-12-games-folder-icon-for-finder/) 
* [earlier macOS versions](https://swissmacuser.ch/games-folder-icon-for-macos-finder/)

(Is .png ok? Could provide other formats if needed… let me know)

Cheers

**Comment by shariati** [comment]
Sorry been very busy lately. I will get back to this project by end of this year. Hopefully during the December holidays.
I will add your icon set.

**Comment by shariati** [comment]
@Swiss-Mac-User Thank you very much for your generous offer. Could you please provide me with a PNG image of the mask game icon? I will include it in the list of masks and acknowledge your contribution in `docs/ATTRIBUTION.md` and `README.md`.

**Comment by shariati** [comment]
Added Additional Icons Associated with Gaming #127
